import React from 'react'
import styles from '../styles/Contact.module.css'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'

const contact = () => {
  return (
    <div className={styles.container}>

      <Head>
        <title>Tech Challenge - Contact</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.left}>
        
      </div>
      
      <div className={styles.right}>

      </div>

    </div>
  )
}

export default contact